name: Docker Image CI & Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zwsq/chealth:${{ github.run_number }}
    - name: Push the Docker image
      run: docker push zwsq/chealth:${{ github.run_number }}
  
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
